URL_SERVICE =  "https://cnt-d00cf47f-70d4-478e-be3f-cc7ca329d696.containerhub.tripleten-services.com"
DOC_PATH =  "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"